version: '3'
services:
  magic:
    image: mageai/mageai:latest
    command: mage start base_project
    #env_file:
    #  - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/src/base_project
    #  ENV: ${ENV}
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
    restart: on-failure:5
